using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Movies : MonoBehaviour
{
    
    public string[,] filmler =
    {
        {"Yarým Elma"               ,"Yerli"},
        {"Asmalý Konak"             ,"Yerli"},
        {"Çiçek Taksi"              ,"Yerli"},
        {"Bizimkiler"               ,"Yerli"},
        {"Hayat Bilgisi"            ,"Yerli"},
        {"Süper Baba"               ,"Yerli"},
        {"Kardeþ Payý"              ,"Yerli"},
        {"Geniþ Aile"               ,"Yerli"},
        {"Cennet Mahallesi"         ,"Yerli"},
        {"Acemi Cadý"               ,"Yerli"},
        {"En Son Babalar Duyar"     ,"Yerli"},
        {"Deli Yürek"               ,"Yerli"},
        {"Susuz Yaz"                ,"Yerli"},
        {"Hababam Sýnýfý"           ,"Yerli"},
        {"Babam ve Oðlum"           ,"Yerli"},
        {"Eþkiya"                   ,"Yerli"},
        {"Caným Kardeþim"           ,"Yerli"},
        {"Selvi Boylum Al Yazmalým" ,"Yerli"},
        {"Yol"                      ,"Yerli"},
        {"Çöpçüler Kralý"           ,"Yerli"},
        {"Tosun Paþa"               ,"Yerli"},
        {"Neþeli Günler"            ,"Yerli"},
        {"Bizim Aile"               ,"Yerli"},
        {"Süt Kardeþler"            ,"Yerli"},
        {"Gelin"                    ,"Yerli"},
        {"Kurtlar Vadisi"           ,"Yerli"},
        {"Düðün Dernek"             ,"Yerli"},
        {"Mavi Boncuk"              ,"Yerli"},
        {"Kabadayý"                 ,"Yerli"},
        {"Fetih 1453"               ,"Yerli"},
        {"Issýz Adam"               ,"Yerli"},
        {"Kapýcýlar Kralý"          ,"Yerli"},
        {"Köyden Ýndim Þehire"      ,"Yerli"},
        {"Uçurtmayý Vurmasýnlar"    ,"Yerli"},
        {"Arabesk"                  ,"Yerli"},
        {"Gülen Gözler"             ,"Yerli"},
        {"Dedemin Ýnsanlarý"        ,"Yerli"},
        {"Her Þey Çok Güzel Olacak" ,"Yerli"},
        {"Malkoçoðlu"               ,"Yerli"},
        {"Kader"                    ,"Yerli"},
        {"Kýþ Uykusu"               ,"Yerli"},
        {"Arkadaþ"                  ,"Yerli"},
        {"Devrim Arabalarý"         ,"Yerli"},
        {"Gönül Yarasý"             ,"Yerli"},
        {"Duvar"                    ,"Yerli"},
        {"Eyyvah Eyvah"             ,"Yerli"},
        {"Organize Ýþler"           ,"Yerli"},
        {"Recep Ývedik"             ,"Yerli"},
        {"Ýnek Þaban"               ,"Yerli"},
        {"Baba"                     ,"Yerli"},
        {"Yahþi Batý"               ,"Yerli"},
        {"Hokkabaz"                 ,"Yerli"},
        {"Dondurmam Gaymak"         ,"Yerli"},
        {"Bizans Oyunlarý"          ,"Yerli"},
        {"Kelebekler Sonsuza Uçar"  ,"Yerli"},
        {"Bal"                      ,"Yerli"},
        {"Arka Sokaklar"            ,"Yerli"},
        {"Çocuklar Duymasýn"        ,"Yerli"},
        {"Acý Tatlý Ekþi"           ,"Yerli"},
        {"Maskeli Beþler"           ,"Yerli"},
        {"Av Mevsimi"               ,"Yerli"},
        {"Gurbet Kuþlarý"           ,"Yerli"},
        {"Büyük Adam Küçük Aþk"     ,"Yerli"},
        {"Boyalý Kuþ"               ,"Yabancý"},
        {"Sefiller"                 ,"Yabancý"},
        {"Bal Ülkesi"               ,"Yabancý"},
        {"Sonsuzluk Üzerine"        ,"Yabancý"},
        {"Burasý Cennet Olmalý"     ,"Yabancý"},
        {"Subay ve Casus"           ,"Yabancý"},
        {"Annelerimiz"              ,"Yabancý"},
        {"Bedenimi Kaybettim"       ,"Yabancý"},
        {"Karanlýk Sular"           ,"Yabancý"},
        {"Elveda"                   ,"Yabancý"},
        {"Küçük Kadýnlar"           ,"Yabancý"},
        {"Býçaklar Çekildi"         ,"Yabancý"},
        {"Yabancý"                  ,"Yabancý"},
        {"Barbarlarý Beklerken"     ,"Yabancý"},
        {"Gentlemen"                ,"Yabancý"},
        {"Yeni Baþtan"              ,"Yabancý"},
        {"Görünmez Adam"            ,"Yabancý"},
        {"Yürüyen Ölüler"           ,"Yabancý"},
        {"Taht Oyunlarý"            ,"Yabancý"},
        {"Thor "                    ,"Yabancý"},
        {"Mezarýna Tüküreceðim "    ,"Yabancý"},
        {"Çýðlýk"                   ,"Yabancý"},
        {"Ejderhaný Nasýl Eðitirsin","Yabancý"},
        {"Kung Fu Panda"            ,"Yabancý"},
        {"Uzun Kabus"               ,"Yabancý"},
        {"Karantina"                ,"Yabancý"},
        {"Ölüm Kitabý"              ,"Yabancý"},
        {"Sessiz Tepe"              ,"Yabancý"},
        {"Patron Bebek"             ,"Yabancý"},
        {"Grinin Elli Tonu"         ,"Yabancý"},
        {"Karanlýðýn Elli Tonu"     ,"Yabancý"},
        {"Saklambaç"                ,"Yabancý"},
        {"Üç Aptal"                 ,"Yabancý"},
        {"Dövüþ Kulübü"             ,"Yabancý"},
        {"Anne"                     ,"Yabancý"},
        {"Zehir"                    ,"Yabancý"},
        {"Su ve Ateþ"               ,"Yabancý"},
        {"Maymunlar Cehennemi"      ,"Yabancý"},
        {"Su Adam"                  ,"Yabancý"},
        {"Son Hava Bükücü"          ,"Yabancý"},
        {"Sessiz"                   ,"Yabancý"},
        {"Temizlikçi"               ,"Yabancý"},
        {"Oda"                      ,"Yabancý"},
        {"Derin Kabus"              ,"Yabancý"},
        {"Karanlýk Saat"            ,"Yabancý"},
        {"Üç Maymun"                ,"Yabancý"},
        {"Hamam"                    ,"Yabancý"},
        {"Pinokyo"                  ,"Yabancý"},
        {"Kabus"                    ,"Yabancý"},
        {"Yedi Kadýn Ve Bir Cinayet","Yabancý"},
        {"Ölüler Ordusu"            ,"Yabancý"},
        {"Matrix"                   ,"Yabancý"},
        {"Kadýn Kokusu"             ,"Yabancý"},
        {"Testere"                  ,"Yabancý"},
        {"Kayýp Balýk Memo"         ,"Yabancý"},
        {"Kötü Kedi Þerafettin"     ,"Yabancý"},
        {"Aslan Kral"               ,"Yabancý"},
        {"Sihirbaz"                 ,"Yabancý"},
        {"King Kong"                ,"Yabancý"},
        {"Güzel Ve Çirkin"          ,"Yabancý"},
        {"300 Spartalý"             ,"Yabancý"},
        {"Halka"                    ,"Yabancý"},
        {"Son Durak"                ,"Yabancý"},
        {"Taþýyýcý"                 ,"Yabancý"},
        {"Koku"                     ,"Yabancý"},
        {"Küfürbaz Haydo"           ,"Yabancý"},
        {"Býçaðýn Ýki Yüzü"         ,"Yabancý"},
        {"Kadýn Kral"               ,"Yabancý"},
        {"Deney"                    ,"Yabancý"},
        {"Ölümcül Deney"            ,"Yabancý"},
        {"Viraj"                    ,"Yabancý"},
        {"Kaðýt"                    ,"Yabancý"},
        {"Ateþten Kalbe Akýldan Dumana" ,"Yabancý"},
        {"Soðuk"                    ,"Yabancý"},
        {"Savaþ Atý"                ,"Yabancý"},
        {"Ejderha Dövmeli Kýz"      ,"Yabancý"},
        {"Demir Adam"               ,"Yabancý"},
        {"Hayvan Mezarlýðý"         ,"Yabancý"},
        {"Ölüm Fýsýltýsý"           ,"Yabancý"},
        {"O Kadýn"                  ,"Yabancý"},
        {"Mesaj"                    ,"Yabancý"},
        {"Gladyator"                ,"Yabancý"},
        {"Aþk Ve Savaþ"             ,"Yabancý"},
        {"Otostopçu"                ,"Yabancý"},
        {"Gölge Ve Kemik"           ,"Yabancý"},
        {"Kýrmýzý Kaplumbaða"       ,"Yabancý"},
        {"Daire"                    ,"Yabancý"},
        {"Göz"                      ,"Yabancý"},
        {"Çarpýþma"                 ,"Yabancý"},
        {"Sarýþýn Bomba"            ,"Yabancý"},
        {"Dövüþçü"                  ,"Yabancý"},
        {"Kurt Kapaný"              ,"Yabancý"},
        {"Peþimdeki Þeytan"         ,"Yabancý"},
        {"Saatler"                  ,"Yabancý"},
        {"Kiracý"                   ,"Yabancý"},
        {"Korkunç Bir Film"         ,"Yabancý"},
        {"Kana Susadým"             ,"Yabancý"},
        {"Yumurta"                  ,"Yabancý"},
        {"Tarzan"                   ,"Yabancý"},
        {"Kýz Ve Kurt"              ,"Yabancý"},
        {"Pamuk Prenses"            ,"Yabancý"},
        {"Ölüm Alfebesi"            ,"Yabancý"},
        {"Bekarlýða Veda"           ,"Yabancý"},
        {"Yeþil Fener"              ,"Yabancý"},
        {"Þah Mat"                  ,"Yabancý"},
        {"Yatak Dersleri"           ,"Yabancý"},
        {"Karanlýk Sular"           ,"Yabancý"},
        {"Uzaða Bak"                ,"Yabancý"},
        {"Sakýn Dinleme"            ,"Yabancý"},
        {"Anons"                    ,"Yabancý"},
        {"Güvercin Hýrsýzlarý"      ,"Yabancý"},
        {"Ölüm Uykusu"              ,"Yabancý"},
        {"Ýçimdeki Þeytan"          ,"Yabancý"},
        {"Kediler Ve Köpekler"      ,"Yabancý"},
        {"Kaplumbaðalar"            ,"Yabancý"},
        {"Aðýr Roman"               ,"Yabancý"},
        {"Ýnþaat"                   ,"Yabancý"},
        {"Kedi Kadýn"               ,"Yabancý"},
        {"Elmalar"                  ,"Yabancý"},
        {"Avatar"                   ,"Yabancý"},
        {"Nefes Nefese"             ,"Yabancý"},
        {"Kara Kule"                ,"Yabancý"},
        {"Nefesini Tut"             ,"Yabancý"},
        {"Salgýn"                   ,"Yabancý"},
        {"Gökdelen"                 ,"Yabancý"},
        {"Forrest Gump"             , "Yabancý"},
        {"Esaretin Bedeli"          , "Yabancý"},
        {"Baþlangýç"                , "Yabancý"},
        {"Kara Þövalye"             , "Yabancý"},
        {"Ucuz Roman"               , "Yabancý"},
        {"Baba"                     , "Yabancý"},
        {"Matrix"                   , "Yabancý"},
        {"Dövüþ Kulübü"             , "Yabancý"},
        {"Gladyatör"                , "Yabancý"},
        {"Aþýklar Þehri"            , "Yabancý"},
        {"Yýldýzlararasý"           , "Yabancý"},
        {"Parazit"                  , "Yabancý"},
        {"Joker"                    , "Yabancý"},
        {"Sosyal Að"                , "Yabancý"},
        {"Büyük Budapeþte Oteli"    , "Yabancý"},
        {"Whiplash"                 , "Yabancý"},
        {"Aslan Kral"               , "Yabancý"},
        {"Coco"                     , "Yabancý"},
        {"Yukarý Bak"               , "Yabancý"},
        {"Kuzularýn Sessizliði"     , "Yabancý"},
        {"Yeþil Yol"                , "Yabancý"},
        {"Yüzüklerin Efendisi"      , "Yabancý"},
        {"Harry Potter"             , "Yabancý"},
        {"Indiana Jones"            , "Yabancý"},
        {"Karayip Korsanlarý"       , "Yabancý"},
        {"Yýldýz Savaþlarý"         , "Yabancý"},
        {"Terminatör"               , "Yabancý"},
        {"Hýzlý ve Öfkeli"          , "Yabancý"},
        {"Görevimiz Tehlike"        , "Yabancý"},
        {"Transformers"             , "Yabancý"},
        {"Örümcek Adam"             , "Yabancý"},
        {"Batman"                   , "Yabancý"},
        {"Superman"                 , "Yabancý"},
        {"Iron Man"                 , "Yabancý"},
        {"Yenilmezler"              , "Yabancý"},
        {"Star Trek"                , "Yabancý"},
        {"Game of Thrones"          , "Yabancý"},
        {"The Witcher"              , "Yabancý"},
        {"Breaking Bad"             , "Yabancý"},
        {"Yarýnýn Sýnýrýnda"        , "Yabancý"},
        {"Jurassic Park"            , "Yabancý"},
        {"Avatar"                   , "Yabancý"},
        {"Yedinci Mühür"            , "Yabancý"},
        {"Casablanca"               , "Yabancý"},
        {"Schindler'in Listesi"     , "Yabancý"},
        {"Geleceðe Dönüþ"           , "Yabancý"},
        {"Yýldýzlararasý"           , "Yabancý"},
        {"Gladyatör"                , "Yabancý"},
        {"Çarpýþma"                 , "Yabancý"},
        {"Zindan Adasý"             , "Yabancý"},
        {"Büyük Hesaplaþma"         , "Yabancý"},
        {"Blade Runner"             , "Yabancý"},
        {"Cesur Yürek"              , "Yabancý"},
        {"Esaretin Bedeli"          , "Yabancý"},
        {"Forrest Gump"             , "Yabancý"},
        {"Inception"                , "Yabancý"},
        {"Titanik"                  , "Yabancý"},
    };
}
